### PR TITLE
[BUGFIX] Use typoscript fileending

### PR DESCRIPTION
**Pull request by benjaminkott**

### CODE REVIEW

**Comment by IchHabRecht** [comment]
Hi @benjaminkott,

As the sitepackage covers TYPO3 7.6 and 8.7 I'm unable to use the typoscript extension.

**Comment by benjaminkott** [comment]
@IchHabRecht this is fine, for me - but the only other avialable official communicated filed extension then would be .txt - i can cadapt the pr if you want.

**Comment by IchHabRecht** [comment]
@benjaminkott I'm not sure what you mean exactly. But having a look into \TYPO3\CMS\Core\TypoScript\TemplateService::getTypoScriptSourceFileContent in a TYPO3 7.6 core shows that .ts is preferred over .txt extension.

**Comment by benjaminkott** [comment]
@IchHabRecht thats correct, but it was never communicated as best practice and the core itself uses for older versions .txt for that reason, since .ts is already reserved for typescript files. 

The .ts fileending for setups was introduced in 2015 (for IDE support) and was merged without checking checking that the .ts fileending was already occupied by typescript since 2012. Thus said it was never used by the core nor communicated publicly as best-practice. 

To finally resolve the issue we introduced .typoscript as fileending that is now the offical successor of .txt.

**Comment by IchHabRecht** [comment]
@benjaminkott thanks for sharing. Will update mask_export then as well.

**Comment by benjaminkott** [comment]
@IchHabRecht thx a lot

**Pull request merged**
